name: Fake Build

on:
  workflow_dispatch:
  
  
  

jobs:
  build-windows:

    outputs:
      upload_url_base64: ${{ steps.b64encode_upload_url.outputs.upload_url_base64 }}

    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2



    - name: update version number
      run: |
        echo 1.0.10.777 > AzerothAuctionAssassin-windows\AzerothAuctionAssassin\Resources\appVersion.txt
    

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.10.777
        release_name: Release v1.0.10.777
        draft: false
        prerelease: false

    - name: Encode and Save Upload URL as Base64
      id: b64encode_upload_url
      run: echo "::set-output name=upload_url_base64::$(echo -n '${{ steps.create_release.outputs.upload_url }}' | base64 --wrap=0)"

    - name: Upload Executable to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: AzerothAuctionAssassin-windows\AzerothAuctionAssassin\Resources\appVersion.txt
        asset_name: AzerothAuctionAssassin.exe
        asset_content_type: application/octet-stream

  build-mac:
    needs: build-windows
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Decode Upload URL
      run: |
        echo "decoded_upload_url=$(echo ${{ needs.build-windows.outputs.upload_url_base64 }} | base64 --decode)" >> $GITHUB_ENV

    - name: Upload macOS Executable to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.decoded_upload_url }}
        asset_path: ./AzerothAuctionAssassin-windows/AzerothAuctionAssassin/Program.cs
        asset_name: AzerothAuctionAssassin-macOS
        asset_content_type: application/octet-stream
